name: norse-venture-hono
on:
  push:
    branches: [master]

jobs:
  docker_build_push:
    name: docker build and push to dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t norse-venture-hono .
      - name: Push the Docker image
        run: docker tag norse-venture-hono ${{ secrets.DOCKERHUB_USERNAME }}/norse_venture_hono:latest
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin <<< "${{ secrets.DOCKERHUB_PASSWORD }}"
      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/norse_venture_hono
